### ISSUE TITLE
shapenet-r2n2.zip doesn't exist in the GDrive

### ISSUE THREAD

**Issue by zzilch** [zhou13/nerd#1]
shapenet-r2n2.zip doesn't exist in the GDrive? Can you share it again?

**Comment by zzilch** [comment]
I find it using the url in the ../misc/gdrive-download.sh

**Comment by njnj0314** [comment]
Hello, I recently read this paper, download the data set encountered some problems, please ask you have this paper data set?

**Comment by zhou13** [comment]
@njnj0314 The link has no problem.
