### ISSUE TITLE
model output?

### ISSUE THREAD

**Issue by 1aq-qa1** [zhou13/nerd#10]
Thank you for a great job.
I would like to ask you, what is the output result of your model? Is w normal to the plane of symmetry or is it a plane of symmetry? I thought it was the normal line of the plane of symmetry, but your resulting visualization shows the plane of symmetry, which is a conflict for me. I'd like to know your answer. Looking forward to your reply!

**Comment by zhou13** [comment]
It is the normal. See Fig 4 and "Scale Ambiguity" section of the paper.
