### ISSUE TITLE
All google drive links are no longer valid

### ISSUE THREAD

**Issue by RyanXLi** [zhou13/nerd#11]
Hi! Thank you for the great work. Unfortunately, all google drive links including data and model seem to be invalid for me. Could you help  update them? This would be immensely helpful for future research. Thanks a lot!

**Comment by zhou13** [comment]
Sorry for the delay. The university cuts off the access to the Google Drive and the files have been uploaded to https://huggingface.co/yichaozhou/nerd.

**Comment by RyanXLi** [comment]
Thank you a lot for the effort!

________________________________
