### ISSUE TITLE
Figures for visualizaton (Fig 7 in the paper/Fig 14 in supp)

### ISSUE THREAD

**Issue by yanconglin** [zhou13/nerd#4]
Hi, Yichao

I was wondering if you can kindly tell me how to generate those nice figures for visualization (e.g. Fig 7 in the paper/Fig 14 in supp). Tried several things using matplotlib, unfortunately still did not figure out. Appreciate it if you can shae the source code to draw them.

BTW, have a nice summer break!

Cheers, 
Yancong

![Screenshot from 2021-08-05 14-20-47](https://user-images.githubusercontent.com/26435516/128349932-91294fe1-c0e9-4900-be4d-5e64c7937be2.png)

**Comment by zhou13** [comment]
The visualization is rendered by projecting a rectangle (the symmetry plane) in pixel by pixel manually. Unfortunately, I think we cannot find that part of the code during code release so we were not able to share it.

**Comment by yanconglin** [comment]
Thanks for the reply. I would assume the red part is also rendered/calculated in the same manner.

**Comment by yanconglin** [comment]
Sorry, one more request: I wonder if you can kindly share the exp results (the raw data to plot curves) of those baselines, as in Fig 6?  Having a hard time to reprodice correct results from those models as most of them are not directly reltaed to symmetry (mostly on camera pose estimation).  
Thank you~

![Screenshot from 2021-08-06 17-52-55](https://user-images.githubusercontent.com/26435516/128537822-5bbf0c4a-65f2-4149-b249-58b3c9468084.png)

**Comment by zhou13** [comment]
@yanconglin Thank you for being interested in our work! I have uploaded the npz files and used to generated to plot to https://drive.google.com/drive/folders/1XFpNVc48oFtG9cjzJ0K4m3IePqDcvAGa. You can use them as a reference.

**Comment by yanconglin** [comment]
Many thanks! BTW, could you please tell me why DISN/NOCS are missing on the pix3d?
